### ISSUE TITLE
panic in eth1deposits

### ISSUE THREAD

**Issue by henridf** [wealdtech/chaind#60]
This is on chaind 0.6.11.  The panic: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb3ca19]

goroutine 250 [running]:
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).blockTimestampByHash(0xc0005c2000, {0xe21250, 0xc02e148cc0}, {0xc031a29340, 0x20, 0x40})
        /home/henridf/chaind/services/eth1deposits/getlogs/blocktimestampbyhash.go:59 +0x219
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).blockHashToTime(0xc0005c2000, {0xe21250, 0xc02e148cc0}, {0xc031a29340, 0x20, 0x40})
        /home/henridf/chaind/services/eth1deposits/getlogs/handler.go:154 +0x105
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).depositFromLogEntry(0xc0005c2000?, {0xe21250, 0xc02e148cc0}, 0xc0004f25a0, 0xc02fbc1e00, 0x0)
        /home/henridf/chaind/services/eth1deposits/getlogs/handler.go:127 +0xa8
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).handleBlocks(0xc0005c2000, {0xe21250, 0xc02d9e1e00}, 0xed18a6, 0xed18b0)
        /home/henridf/chaind/services/eth1deposits/getlogs/handler.go:59 +0x1dd
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).parseNewBlocks(0xc0005c2000, {0xe211a8, 0xc0001d21c0}, 0xc00557fd20)
        /home/henridf/chaind/services/eth1deposits/getlogs/service.go:234 +0x5e5
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).checkLatestBlock(0xc010b25f88?, {0xe211a8, 0xc0001d21c0})
        /home/henridf/chaind/services/eth1deposits/getlogs/service.go:195 +0x92
github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).updateAfterRestart.func1({0xe211a8, 0xc0001d21c0}, 0x0?)
        /home/henridf/chaind/services/eth1deposits/getlogs/service.go:169 +0x45
created by github.com/wealdtech/chaind/services/eth1deposits/getlogs.(*Service).updateAfterRestart
        /home/henridf/chaind/services/eth1deposits/getlogs/service.go:165 +0x271
```

And some error logs that happened a few minutes before the panic: 

```
{"level":"warn","service":"eth1deposits","impl":"getlogs","start_block":15538302,"end_block":15538311,"error":"failed to set ETH1 deposit: ERROR: null value in column \"f_eth1_sender\" of relation \"t_eth1_deposits\" violates not-null constraint (SQLSTATE 23502)","time":"2022-09-15T09:48:43Z","message":"Failed to update ETH1 deposits"}
{"level":"warn","service":"eth1deposits","impl":"getlogs","start_block":15538312,"end_block":15538321,"error":"failed to set ETH1 deposit: ERROR: null value in column \"f_eth1_sender\" of relation \"t_eth1_deposits\" violates not-null constraint (SQLSTATE 23502)","time":"2022-09-15T09:50:46Z","message":"Failed to update ETH1 deposits"}
```

I'll be happy to put up a PR for this but won't be before a couple days.

**Comment by mcdee** [comment]
Thank you for reporting this, it has been fixed in release 0.6.14
